Repository CMU-313/fall-2021-hw2-crabs-adjust-humidity, pull requests merged in 2021-09, with the labels that each got.

#2 Darkened the danger color of button to increase contrast with text color
  mayan/apps/appearance/static/appearance/css/base.css
Labels: hw1

#8 Deferred non-critical CSS
  mayan/apps/appearance/templates/appearance/base_plain.html
  mayan/apps/appearance/templates/appearance/root.html
Labels: hw1

#10 Yuzhou Wang Dashboard Contrast
  mayan/apps/dashboards/templates/dashboards/numeric_widget.html
  mayan/apps/dynamic_search/templates/dynamic_search/search_box.html
Labels: hw1

#21 improve dropdown in reviewer assignment
  mayan/apps/appearance/templates/appearance/generic_list_items_dropdown_subtemplate.html
  mayan/apps/documents/views/reviewer_management_views.py
Labels: enhancement

#24 Adding file containing steps to test reviewer dashboard feature
  README.md
  docs/testing_reviewer_dashboard.txt
Labels: documentation

#26 write document to introduce new feature
  docs/reviewer_assignment.txt
Labels: documentation

#27 Added links to documentation and testing to README for reviewer dashb…
  README.md
Labels: documentation

#32 Update testing doc to reflect new changes
  docs/testing_reviewer_dashboard.txt
Labels: documentation

#31 Revise documentation
  docs/_static/Inkedlogin_LI.jpg
  docs/_static/dropdown.png
  docs/_static/main_side.png
  docs/_static/main_widget.png
  docs/_static/re_ma.png
  docs/reviewer_assignment.md
Labels: documentation

#28 Added support for multiple reviewer selection and removed unnecessary navigation
  mayan/apps/appearance/templates/appearance/generic_list_items_dropdown_subtemplate.html
  mayan/apps/documents/views/reviewer_management_views.py
Labels: enhancement
